# python train.py -mode train -encoder transformer -dropout 0.1 -bert_data_path ../bert_data/cnndm -model_path ../models/bert_transformer_50000 -lr 2e-3 -visible_gpus 0  -gpu_ranks 0 -world_size 1 -report_every 100 -save_checkpoint_steps 5000 -batch_size 3000 -decay_method noam -train_steps 50000 -accum_count 2 -log_file ../logs/bert_transformer_train_50000 -use_interval true -warmup_steps 10000 -ff_size 2048 -inter_layers 2 -heads 8;
# python train.py -mode test -test_from /home/wjm/hrx/BertSum/models/bert_transformer_50000/model_step_50000.pt -log_file ../logs/bert_transformer_test-50000 -result_path /home/wjm/hrx/BertSum_cnndm/results/cnndm_transformer;
#python train.py -mode test -test_from /home/wjm/hrx/BertSum/models/bert_transformer/model_step_9000.pt -log_file ../logs/bert_transformer_test-9000;
python train.py -mode train -encoder classifier -dropout 0.1 -bert_data_path ../bert_data/cnndm -model_path ../models/bert_classifier_35000 -lr 2e-3 -visible_gpus 0  -gpu_ranks 0 -world_size 1 -report_every 100 -save_checkpoint_steps 5000 -batch_size 3000 -decay_method noam -train_steps 35000 -accum_count 2 -log_file ../logs/bert_classifier_train_35000 -use_interval true -warmup_steps 10000;
python train.py -mode test -test_from /home/wjm/hrx/BertSum_cnndm/models/bert_classifier_35000/model_step_35000.pt -log_file ../logs/bert_classifier_test-35000 -result_path /home/wjm/hrx/BertSum_cnndm/results/cnndm_classifier;
#python train.py -mode test -test_from /home/wjm/hrx/BertSum/models/bert_classifier/model_step_9000.pt -log_file ../logs/bert_classifier_test-9000;
python train.py -mode train -encoder rnn -dropout 0.1 -bert_data_path ../bert_data/cnndm -model_path ../models/bert_rnn_35000 -lr 2e-3 -visible_gpus 0  -gpu_ranks 0 -world_size 1 -report_every 100 -save_checkpoint_steps 5000 -batch_size 3000 -decay_method noam -train_steps 35000 -accum_count 2 -log_file ../logs/bert_rnn_train_35000 -use_interval true -warmup_steps 10000 -rnn_size 768 -dropout 0.1;
python train.py -mode test -test_from /home/wjm/hrx/BertSum_cnndm/models/bert_rnn_35000/model_step_35000.pt -log_file ../logs/bert_rnn_test-35000 -result_path /home/wjm/hrx/BertSum_cnndm/results/cnndm_rnn;
#python train.py -mode test -test_from /home/wjm/hrx/BertSum/models/bert_rnn/model_step_9000.pt -log_file ../logs/bert_rnn_test-9000;

python train.py -mode train -encoder baseline -dropout 0.1 -bert_data_path ../bert_data/cnndm -model_path ../models/bert_baseline_35000 -lr 2e-3 -visible_gpus 0  -gpu_ranks 0 -world_size 1 -report_every 100 -save_checkpoint_steps 5000 -batch_size 3000 -decay_method noam -train_steps 35000 -accum_count 2 -log_file ../logs/bert_baseline_train_35000 -use_interval true -warmup_steps 10000 -dropout 0.1;
python train.py -mode test -test_from /home/wjm/hrx/BertSum_cnndm/models/bert_baseline_35000/model_step_35000.pt -log_file ../logs/bert_baseline_test-35000 -result_path /home/wjm/hrx/BertSum_cnndm/results/cnndm_baseline;

# python train.py -mode train -encoder rnn -dropout 0.1 -bert_data_path ../bert_data/cnndm -model_path ../models/bert_rnn -result_path ../results/cnndm_rnn -lr 2e-3 -visible_gpus 0  -gpu_ranks 0 -world_size 1 -report_every 50 -save_checkpoint_steps 100 -batch_size 3000 -decay_method noam -train_steps 1000 -accum_count 2 -log_file ../logs/bert_rnn_train -use_interval true -warmup_steps 200 -rnn_size 768 -dropout 0.1

# python train.py -mode train -encoder rnn -dropout 0.1 -bert_data_path ../bert_data/cnndm -model_path ../models/bert_rnn -result_path ../results/cnndm_rnn -lr 2e-3 -visible_gpus 0  -gpu_ranks 0 -world_size 1 -report_every 50 -save_checkpoint_steps 1000 -batch_size 3000 -decay_method noam -train_steps 10000 -accum_count 2 -log_file ../logs/bert_rnn_train -use_interval true -warmup_steps 2000 -rnn_size 768 -dropout 0.1;
# python train.py -mode test -test_from /home/wjm/hrx/BertSum/models/bert_rnn/model_step_10000.pt -log_file ../logs/bert_rnn_test-10000 -result_path ../results/cnndm_rnn;
# python train.py -mode test -test_from /home/wjm/hrx/BertSum/models/bert_rnn/model_step_9000.pt -log_file ../logs/bert_rnn_test-9000 -result_path ../results/cnndm_rnn;

